# Generated by Django 4.2.19 on 2025-03-12 17:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buffer_radius', models.FloatField()),
                ('service_area', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('population_served', models.IntegerField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.healthcarefacility')),
            ],
        ),
    ]
