# Generated by Django 4.2.19 on 2025-03-13 10:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_facilityservicearea'),
    ]

    operations = [
        migrations.CreateModel(
            name='KenyaConstituency',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('const_no', models.IntegerField()),
                ('const_name', models.CharField(max_length=100)),
                ('county_nam', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'kenya_constituencies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KenyaCounty',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('county', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'kenya_counties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KenyaWard',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('ward', models.CharField(max_length=100)),
                ('subcounty', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('uid', models.CharField(max_length=100)),
                ('pop2009', models.IntegerField()),
            ],
            options={
                'db_table': 'kenya_wards',
                'managed': False,
            },
        ),
    ]
