# Generated by Django 4.2.19 on 2025-03-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_kenyaconstituency_kenyacounty_kenyaward'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationDensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('year', models.IntegerField()),
                ('raster_file', models.FileField(upload_to='population_density/')),
                ('source', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Population Density Datasets',
            },
        ),
    ]
