# Generated by Django 4.2.19 on 2025-03-12 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('population', models.IntegerField()),
                ('area_km2', models.FloatField()),
                ('population_density', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('population', models.IntegerField()),
                ('area_km2', models.FloatField()),
                ('population_density', models.FloatField()),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.consituency')),
            ],
        ),
    ]
